version: '3.7'

services:

  stringsite:
    image: stringsite
    restart: unless-stopped
    container_name: stringsite
    build: ./
    ports:
      - 3006:3006

      
networks:
  default:
    external:
      name: my-net